spring:
  datasource:
    url: ${DB_URL:${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}}
    username: ${DB_USERNAME:${DATABASE_USERNAME:postgres}}
    password: ${DB_PASSWORD:${DATABASE_PASSWORD:}}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.badminton.academy: DEBUG
    org.springframework.security: DEBUG

app:
  seed-data: false
